### ISSUE TITLE
Support for submenu

### ISSUE THREAD

**Issue by panda-z** [olOwOlo/hugo-theme-even#126]
https://gohugo.io/content-management/menus/#nesting

**Comment by do-me** [comment]
How do you guys handle submenus at the moment? I assume that this feature doesn't exist yet and that it needs a "dirty" workaround by using some custom js or similar. 
Any proposal of how to do this at the moment? 
Thanks a lot!

**Comment by panda-z** [comment]
Seems no one is working on this feature.

**Comment by do-me** [comment]
For anyone still looking for a way to implement submenus or dropdown menus in for this theme, just follow this simple guide.


![image](https://user-images.githubusercontent.com/47481567/125160528-b2b06b80-e17d-11eb-9e5a-9ac99a869ce4.png)


For my use case I wanted 3 different menu parts:
1. The blog section including archives etc. 
2. The main menu section for other stuff.
3. The static pages like "about" and "portfolio"

To achieve this, 3 files need to be created or altered.

1. Create `layouts\partials\header.html` by copying the original file from the `themes` folder. If you do this, hugo will automatically use your tweaked file. (The quickest and dirtiest hack would be to hardcode it here, however this is a nicer and universal way)

Copy the following lines:

```html
<div class="logo-wrapper">
  <a href="{{ "/" | relLangURL }}" class="logo">
    {{- if .Site.Params.logoTitle -}}
      {{ .Site.Params.logoTitle }}
    {{- else -}}
      {{ .Site.Title }}
    {{- end -}}
  </a>
</div>

<nav class="site-navbar">
  <ul id="menu" class="menu">

<!-- Dropdown Menu Tweak-->    
    <div class="dropdown">
      <li class="menu-item">
         <a class="menu-item-link" href="/">Blog</a>
      </li>
      <div class="dropdown-content">
        {{ range .Site.Menus.drop -}}
        <a class="menu-item-link" href="{{ .URL | safeURL }}">{{ .Name }}</a>
        {{- end }}
      </div>    
    </div>

<!-- Normal Menu, includes static pages like e.g. "about"-->
    {{ range .Site.Menus.main -}}
      <li class="menu-item">
        <a class="menu-item-link" href="{{ .URL | safeURL }}">{{ .Name }}</a>
      </li>
    {{- end }}
  </ul>
</nav>

{{ range .Site.Params.customCSS -}}
    <link rel="stylesheet" href="{{ . | absURL }}">
{{- end }}
```

2. Create or alter the custom css in `static\css\evencustom.css`

```css
/* css tweak for dropdown menu */

/* Dropdown Button */
  
  /* The container <div> - needed to position the dropdown content */
  .dropdown {
    position: relative;
    display: inline-block;
  }
  
  /* Dropdown Content (Hidden by Default) */
  .dropdown-content {
    margin-left: 30px;
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
  }
  
  /* Links inside the dropdown */
  .dropdown-content a {

    padding: 12px 16px;
    text-decoration: none;
    display: block;
  }
  
  /* Change color of dropdown links on hover */
  .dropdown-content a:hover {background-color: #ddd;}
  
  /* Show the dropdown menu on hover */
  .dropdown:hover .dropdown-content {display: block;}

.menu-item{
  margin-left: 30px !important;
}
```

3. Alter the menu section in the config file `config.toml`

```toml

# config your menu              # 配置目录

[[menu.drop]]
  name = "Latest"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.drop]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.drop]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.drop]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"

```

and link the custom css

```toml
  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ["evencustom.css"]
  customJS = []
```

Using this logic you can create as many dropdown menus as you wish. Let me know if you have any questions! 
Maybe someone would like to tidy up this logic and create a pull request.
