### ISSUE TITLE
Enable customizing the logo font family

### ISSUE THREAD

**Issue by mbrukman** [olOwOlo/hugo-theme-even#179]
Thanks for making this theme, it looks very nice!

Looks like the Chancery font is right now [hard-coded in the theme][font-face]:

```css
// Font family: Chancery
@font-face {
  font-family: 'Chancery';
  src: url('../fonts/chancery/apple-chancery-webfont.eot');
  src: local('Apple Chancery'), url('../fonts/chancery/apple-chancery-webfont.eot?#iefix') format('embedded-opentype'),
  url('../fonts/chancery/apple-chancery-webfont.woff2') format('woff2'),
  url('../fonts/chancery/apple-chancery-webfont.woff') format('woff'),
  url('../fonts/chancery/apple-chancery-webfont.ttf') format('truetype'),
  url('../fonts/chancery/apple-chancery-webfont.svg#apple-chancery') format('svg');
  font-weight: lighter;
  font-style: normal;
}
```

[and also][logo-font-family]:

```css
// Font family of the logo.
$logo-font-family: 'Chancery', cursive, LiSu, sans-serif !default;
```

Would it be possible to make this parameterized so it's possible to try out a different logo font with just a single line in the config? If so, can you please provide an example of how to do this?

Or is the only way to change this is to branch this CSS file and modify it locally?

---

Also, it looks like this repo includes a [local copy of the Chancery font][chancery-local], what benefit does it provide over using Google Fonts API? Is it faster / more efficient to serve all elements (HTML, CSS, fonts) from the same location as the blog itself?

[font-face]: https://github.com/olOwOlo/hugo-theme-even/blob/8ce9bce7714bd9c6c70624ec4603c437f2bda3e4/src/css/_variables.scss#L81-L92
[logo-font-family]: https://github.com/olOwOlo/hugo-theme-even/blob/8ce9bce7714bd9c6c70624ec4603c437f2bda3e4/src/css/_variables.scss#L97-L98
[chancery-local]: https://github.com/olOwOlo/hugo-theme-even/tree/3c6cb7f29631dfcdd954e7cbd5d2370efe7eb827/src/fonts/chancery
