### ISSUE TITLE
英文引号被错误渲染为中文引号

### ISSUE THREAD

**Issue by laggardkernel** [olOwOlo/hugo-theme-even#206]
即便配置Hugo为英文语言。

```toml
languageCode = "en"
defaultContentLanguage = "en"
hasCJKLanguage = false
```

文章中英文引号依然被渲染为中文引号。
