### ISSUE TITLE
最新版似乎有个bug：文章目录无法支持3级标题以下的显示

### ISSUE THREAD

**Issue by zhahuya** [olOwOlo/hugo-theme-even#240]
文章的目录导航只能显示3级以上的标题，以下的不显示。
我在最干净的文件夹里 git clone 了最新的主题文件进行测试，重现了这个问题。
我看了半天toc.html文件，看不懂QAQ，有没有大佬顺手解决一下。

**Comment by panda-z** [comment]
@zhahuya 
Hugo (>=0.60.0) uses Goldmark as default renderer.
You may add the following settings to your `config.toml`.
```toml
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
```
See https://gohugo.io/getting-started/configuration-markup/#table-of-contents
