### ISSUE TITLE
code block is not rendered correctly

### ISSUE THREAD

**Issue by woodwm** [olOwOlo/hugo-theme-even#276]
Using the latest version of hugo `0.71.1`, the code block is not rendered correctly. Please see the example of a coe block using the file `even-preview.md`.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/13971199/83309922-3544c880-a213-11ea-9dd3-ce81df979948.png">

**Comment by panda-z** [comment]
Try to add the following settings to your `config.toml`

```
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true             # New since 0.60, optional, allows HTML inside CommonMark content
```

**Comment by dds2333** [comment]
> Using the latest version of hugo `0.71.1`, the code block is not rendered correctly. Please see the example of a coe block using the file `even-preview.md`.
> 
> <img alt="image" width="784" src="https://user-images.githubusercontent.com/13971199/83309922-3544c880-a213-11ea-9dd3-ce81df979948.png">

or add the following setting:
[markup]
  defaultMarkdownHandler = "blackfriday"

see also：https://jdhao.github.io/2019/12/29/hugo_html_not_shown/

**Comment by TenZeroTwo** [comment]
You may have made the same mistake as me. Enable  the different highlight methods in the same time.
```toml
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
... ...
  highlightInClient = true
```
**Be corrent as below:**
```toml
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
... ...
  highlightInClient = false
```
**OR**
```toml
# pygmentsOptions = "linenos=table"
# pygmentsCodefences = true
# pygmentsUseClasses = true
# pygmentsCodefencesGuessSyntax = true
... ...
  highlightInClient = true
```
