### ISSUE TITLE
Add margin to paragraphs in blockquote?

### ISSUE THREAD

**Issue by dmjones** [olOwOlo/hugo-theme-even#280]
The default CSS has zero margin for paragraphs in a quote.

Wouldn't it be better to have standard margins here? Something like:

```css
.post .post-content blockquote p:not(:last-child) {
    margin-bottom: 1em;
}
```
