### ISSUE TITLE
toc线上环境无法展示 本地可以

### ISSUE THREAD

**Issue by tim0991** [olOwOlo/hugo-theme-even#287]
eg: https://tim0991.github.io/post/2020/06/30/how-to-pack-file-into-binary/
github: https://github.com/tim0991/blog

**Comment by tim0991** [comment]
先上结论
```toml
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
```
startLevel改成1即可生成

由于作者没回复我，我又对hugo不了解就抽空看了一下末班，发现toc是hugo生成，顺手搜了一下issue，发现已有人回复 https://github.com/olOwOlo/hugo-theme-even/issues/240#issuecomment-613780708

本地hugo 0.59
travis 0.73
加上之后就好了
