### ISSUE TITLE
对于较长的数学公式

### ISSUE THREAD

**Issue by niu-niu** [olOwOlo/hugo-theme-even#32]
在手机端(4.7寸屏幕)上，较长的数学公式会直接向右超出边界，而不是和文字一起规约在一定的页宽内。是不是我哪里没有设置好?看到其他主题默认情况下也会出现这样的问题。先谢过up主了。

**Comment by olOwOlo** [comment]
修复了行间公式，溢出的内容会出现滚动条

如果还需要应用到行内公式，可以定义一个 customCSS 添加下面的代码（会有一点副作用，所有公式的位置都会出现一些**小**偏移）
```css
.post .post-content .MathJax_CHTML {
  max-width: 100%;
  overflow-x: auto;
  overflow-y: hidden;
  vertical-align: middle;
}
```

如果有更好的方法，还望指点(〃ﾉωﾉ)
