### ISSUE TITLE
homepage 沒有顯示文章

### ISSUE THREAD

**Issue by amikai** [olOwOlo/hugo-theme-even#363]
如題 homepage 沒有顯示文章，但是 archives, tags, categories 皆顯示正常

config.yml
```
baseURL: "https://amikai.github.io"
title: amikai's blog
theme: hugo-theme-even
IsMultiLingual: true
defaultContentLanguage: zh
languages:
  en:
    languageName: English
    languageCode: en-us
  zh:
    languageName: 繁體中文
    languageCode: zh-tw
permalinks:
  posts: /:year/:month/:day/:filename/

hasCJKLanguage: true
paginate: 10

params:
  version: 4.x
  description: "amikai's blog, my learning notes about backend, golang, (neo)vim, k8s, etc."
  utterances:
    owner: amikai
    repo: my_hugo_blog_utterances
  social:
    g-github: "https://github.com/amikai"
    e-linkedin: "https://www.linkedin.com/in/yun-kai-chuang-122064a5/"
  showLanguageSelector: true
  archivePaginate: 50

  fancybox: true

menu:
  main:
    - name: Home
      weight: 10
      identifier: "home"
      url: /
    - name: Archive
      url: /posts/
      weight: 20
    - name: Tags
      url: /tags/
      weight: 30
    - name: Categories
      url: /categories/
      weight: 40
```
在 local 端的預覽如下
<img width="1680" alt="CleanShot 2021-08-18 at 11 11 59@2x" src="https://user-images.githubusercontent.com/13815956/129830886-6bb419c8-04c8-4b74-acc0-a1f6f0d73b43.png">
```
.
├── archetypes
│   └── default.md
├── config.yml
├── content
│   ├── archives.en.md
│   ├── archives.zh.md
│   └── posts
│       ├── hello-world
│       │   ├── index.en.md
│       │   ├── index.zh.md
│       │   └── test.png
├── resources
└── themes
    ├── PaperMod
    ├── hugo-theme-even
```
