### ISSUE TITLE
將 archives 的網址改為 /archives/

### ISSUE THREAD

**Issue by amikai** [olOwOlo/hugo-theme-even#364]
請問 archives 的網址為 /posts/ 如何使用 /archives/ 作為網址 目前這樣設定是不成功的
```
menu:
  main:
    - name: Home
      weight: 10
      identifier: home
      url: /
    - name: Archives
      identifier: archives
      weight: 20
      url: /archives/
    - name: Tags
      identifier: tags
      weight: 30
      url: /tags/
    - name: Categories
      identifier: categories
      weight: 40
      url: /categories/
```
