### ISSUE TITLE
归档页没有博文总数

### ISSUE THREAD

**Issue by zhaozhiyuan1989** [olOwOlo/hugo-theme-even#46]
博客中有 `共计x个分类` `共计x个标签` ，但是没有 `共计x篇文章`

**Comment by olOwOlo** [comment]
有的，但是原主题隐藏了这个内容，所有我也没有变。
以后我考虑弄成可配置的。

现在可以在你的 custom css 中添加下面的代码来显示：

```css
.archive .archive-title .archive-post-counter {
  display: inline;
}
```
