### ISSUE TITLE
[Feature Request] Add search

### ISSUE THREAD

**Issue by jerry011235** [olOwOlo/hugo-theme-even#70]
参考：http://rs.luminousspice.com/hugo-site-search/

**Comment by zhuatw** [comment]
这个可以有, 支持!

**Comment by olOwOlo** [comment]
An awesome implement http://blog.wo-class.cn/

Based on this, we should add:

- Display in mobile screen
- Redirect to search engine after press `Enter`
- Params

    ```toml
    [params.search]
      enable = true
      # Genate a json file include all of your posts, you should not enable this if have too many posts.
      generateIndex = false
      # Redirect to search engine
      searchEngine = "https://www.google.com/search?q=site:yourdomian.com %s" # or false
    ```
