### ISSUE TITLE
Disable link animations

### ISSUE THREAD

**Issue by schiorean** [olOwOlo/hugo-theme-even#75]
Hi,

Is it possible to disable link hover without modifying the /src & rebuilding?

Thanks!

**Comment by olOwOlo** [comment]
Which link?

I assume you are talking about the link in post content and you want to remove the underscore.

Add the following code to your custom css

```css
.post .post-content a:hover {
    border-bottom: none;
}
```

**Comment by schiorean** [comment]
I mean that underline animation, when you hover the mouse over a link. There is that bottom border extending from center to the left and right.

Thanks I will try your solution!

**Comment by schiorean** [comment]
Actually my goal is to make it a usual underline border on hover, just without that animation.

**Comment by olOwOlo** [comment]
You can reset the `transition-duration`, see also https://developer.mozilla.org/en-US/docs/Web/CSS/transition-duration

```css
.post .post-header .post-link:before {
  -webkit-transition-duration: initial;
  transition-duration: initial;
}

.header .site-navbar .menu .menu-item:before {
  -webkit-transition-duration: initial;
  transition-duration: initial;
}
```
