### ISSUE TITLE
有没有考虑增加Valine评论系统

### ISSUE THREAD

**Issue by whf5566** [olOwOlo/hugo-theme-even#95]
有没有考虑增加Valine评论系统

**Comment by olOwOlo** [comment]
不考虑， 欢迎 pr 到 next 分支

**Comment by smslit** [comment]
@olOwOlo 我自己加上并使用了 **valine**，写了一个文章[hugo博客添加评论系统Valine](https://www.smslit.top/2018/07/08/hugo-valine/)

**Comment by whf5566** [comment]
@smslit 
给olOwOlo提交个PR,把valine添加到下个版本中?

**Comment by smslit** [comment]
@whf5566 不知道为啥不能 fork这个项目，很奇怪！更改比较简单（只是在`layouts/partials/comments.html`中添加了[valine](
https://valine.js.org/)相关内容 ），那索性直接给你我修改后的主题文件吧，[点我](http://p9fh104m8.bkt.clouddn.com/share/even.zip)下载，是在 master 分支 3.2.0 版本的基础上添加的 [valine](
https://valine.js.org/)，直接参考 `exampleSite/config.toml` 中第120～131行进行配置，只需更改你自己的 `appId` 和 `appKey` 即可，在这里也贴出 [valine](
https://valine.js.org/) 的配置内容吧：

```toml
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
    enable = true
    appId = ''
    appKey = ''
    notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = '' 
    placeholder = '说点什么吧...'
    visitor = true
```
