### ISSUE TITLE
请教下，alertNote 和 admonition 这两个 shortcode 要怎么配置才能使用

### ISSUE THREAD

**Issue by iterateself** [olOwOlo/hugo-theme-even#96]
看了 https://blog.olowolo.com/post/generate-json-api-and-graphql-api-by-elide-and-spring/

觉得 admonition  很好看，要怎么配置才能使用呢？好像没有这个 template。

**Comment by olOwOlo** [comment]
这个我还没弄完、icon 还没加上去、应该会放进 4.0 里面，下面👇是现在的代码

```css
.admonition{box-shadow:0 2px 2px 0 rgba(0,0,0,0.14),0 1px 5px 0 rgba(0,0,0,0.12),0 3px 1px -2px rgba(0,0,0,0.2);position:relative;margin:.9765em 0;padding:0 .75rem;border-left:.25rem solid #448aff;border-radius:.125rem;overflow:auto}.admonition .admonition-title{margin:0 -0.75rem;padding:.5rem .75rem .5rem 2.5rem;border-bottom:0.1rem solid rgba(68,138,255,0.1);background-color:rgba(68,138,255,0.1);font-weight:700}.admonition .admonition-title:before{position:absolute;left:.75rem}.admonition.note{border-left-color:#448aff}.admonition.note .admonition-title:before{color:#448aff;content:"N"}.admonition.abstract{border-left-color:#00b0ff}.admonition.abstract .admonition-title{background-color:rgba(0,176,255,0.1)}.admonition.abstract .admonition-title:before{color:#00b0ff;content:"A"}.admonition.info{border-left-color:#00b8d4}.admonition.info .admonition-title{background-color:rgba(0,184,212,0.1)}.admonition.info .admonition-title:before{color:#00b8d4;content:"I"}.admonition.tip{border-left-color:#00bfa5}.admonition.tip .admonition-title{background-color:rgba(0,191,165,0.1)}.admonition.tip .admonition-title:before{color:#00bfa5;content:"T"}.admonition.success{border-left-color:#00c853}.admonition.success .admonition-title{background-color:rgba(0,200,83,0.1)}.admonition.success .admonition-title:before{color:#00c853;content:"S"}.admonition.question{border-left-color:#64dd17}.admonition.question .admonition-title{background-color:rgba(100,221,23,0.1)}.admonition.question .admonition-title:before{color:#64dd17;content:"Q"}.admonition.warning{border-left-color:#ff9100}.admonition.warning .admonition-title{background-color:rgba(255,145,0,0.1)}.admonition.warning .admonition-title:before{color:#ff9100;content:"W"}.admonition.failure{border-left-color:#ff5252}.admonition.failure .admonition-title{background-color:rgba(255,82,82,0.1)}.admonition.failure .admonition-title:before{color:#ff5252;content:"F"}.admonition.danger{border-left-color:#ff1744}.admonition.danger .admonition-title{background-color:rgba(255,23,68,0.1)}.admonition.danger .admonition-title:before{color:#ff1744;content:"D"}.admonition.bug{border-left-color:#f50057}.admonition.bug .admonition-title{background-color:rgba(245,0,87,0.1)}.admonition.bug .admonition-title:before{color:#f50057;content:"B"}.admonition.example{border-left-color:#651fff}.admonition.example .admonition-title{background-color:rgba(101,31,255,0.1)}.admonition.example .admonition-title:before{color:#651fff;content:"E"}.admonition.quote{border-left-color:#9e9e9e}.admonition.quote .admonition-title{background-color:rgba(158,158,158,0.1)}.admonition.quote .admonition-title:before{color:#9e9e9e;content:"Q"}.admonition:last-child{margin-bottom:.75rem}details.admonition summary{display:block;outline:none;cursor:pointer}details.admonition summary::-webkit-details-marker{display:none}details.admonition summary:after{position:absolute;top:.5rem;right:.75rem;color:rgba(0,0,0,0.26);content:"U"}details.admonition[open]>summary:after{transform:rotate(180deg)}
```

```go-template-html
{{ if .IsNamedParams -}}

  {{ if eq (.Get "details") "true" -}}

<details class="admonition {{ .Get "type" }}">
  {{- with .Get "title" }}<summary class="admonition-title">{{ . }}</summary>{{ end }}
  {{ .Inner }}
</details>

  {{- else -}}

<div class="admonition {{ .Get "type" }}">
  {{- with .Get "title" }}<p class="admonition-title">{{ . }}</p>{{ end }}
  {{ .Inner }}
</div>

  {{- end }}

{{- else -}}

  {{ if eq (.Get 2) "true" -}}

<details class="admonition {{ .Get 0 }}">
  {{- with .Get 1 }}<summary class="admonition-title">{{ . }}</summary>{{ end }}
  {{ .Inner }}
</details>

  {{- else -}}

<div class="admonition {{ .Get 0 }}">
  {{- with .Get 1 }}<p class="admonition-title">{{ . }}</p>{{ end }}
  {{ .Inner }}
</div>

  {{- end }}

{{- end }}
```
